### ISSUE TITLE
Do you really remove sprockets from this project?

### ISSUE THREAD

**Issue by valterbarros** [progapandist/evil_chat#12]
I see on your awesome post that the sprockets will be all removed from, but I see this line on your gemfile.lock.
 
https://github.com/progapandist/evil_chat/blob/a923f898940fb54c24b9c2d9e898aa0548e1b69e/Gemfile.lock#L91

**Comment by progapandist** [comment]
Hi! The sprockets are indeed no longer there, if you notice they are in `production` group only in Gemfile, currently commented out. Sometimes you may want to enable them (for production environment only), so Heroku knows how to build an app. We figured another way to do so, by "hacking" an `assets:precompile` task, but I guess there are traces left in the Gemfile :) Nothing to worry about though, we are still Sprockets-free :)

**Comment by valterbarros** [comment]
@progapandist wow nice, thank you for clarification, and the post help me so much to get the webpacker gem and other stuffs about modern web development with rails.
