### ISSUE TITLE
Evil Front Part 1: Modern Front-end in Rails | First command fails to produce desired files/config.

### ISSUE THREAD

**Issue by marvindanig** [progapandist/evil_chat#15]
```
$ rails new evil_chat --skip-coffee --skip-sprockets --skip-turbolinks --webpack --database=postgresql  -T
```
This command didn't quite produce `.babelrc`, `.postcssrc.yml`, `package.json` or even the `app/javascripts` folder on my local. I have `ruby 2.5.0p0 + rails 5.1.6 + node 9.8.0` on my machine.

**Comment by ghost** [comment]
Are you installed Yarn? run ` brew install yarn` first

**Comment by marvindanig** [comment]
Dang! Didn't think of it then. Will give it a try soon, thanks!
