### ISSUE TITLE
How do you deal with fragment caching?

### ISSUE THREAD

**Issue by oboxodo** [progapandist/evil_chat#16]
Great article 👏 

Rails has this nice ability to automatically calculate a partials dependency tree and include a hash of it in fragment caching keys. But it depends on recognizing the partial names in the `render` calls and is unable to detect changes in helpers nor partials rendered from helpers which is basically the core of the `component` helper.

The only workaround I can think of is adding a [template dependency](http://guides.rubyonrails.org/v5.1/caching_with_rails.html#explicit-dependencies) comment line mentioning the component partial each time I call the component helper but that kinda defeats the purpose of the helper.

Any ideas?

**Comment by progapandist** [comment]
Hi! There's a great [project](https://github.com/komposable/komponent) inspired by this series of articles and they seem to have implemented caching, see if [that](https://github.com/komposable/komponent/blob/7c9bc98385e360093e55f0c097f9a0272cb22c1f/README.md#component-caching) and its implementation is what you're looking for.

**Comment by oboxodo** [comment]
Thanks for your prompt response @progapandist.

Yeah, I've seen komponent but haven't tried it just yet. We're not ready to make the move to webpack yet but as a first step I was implementing a helper very similar to the `component` one you have here and I was faced with the problem that my changes to the view template weren't expiring any fragment cache where the component partial was included.

I took a look at the caching solution implemented in komponent and I'm not a big fan of it. It's good that it considers the locals being used for example, but it ends up [rendering the passed block](https://github.com/komposable/komponent/blob/d519a85e81b2b390cdd47917ae51ac5838f3e7ef/lib/komponent/component_renderer.rb#L20) in order to calculate the cache_key, thus pretty much defeating the purpose of the cache. On top of that, this solves caching for a specific component but it doesn't play well with Rails' own fragment caching. Rendering a component inside a `cache` call, won't expire the cached fragment if I change the component partial.

This made me research a bit how Rails itself does this. It seems to me that extending the default `ERBTracker` to not only [look for `render` calls](https://github.com/rails/rails/blob/052fcef0cb405a3fa3a46349a9d979c2e0d4c160/actionview/lib/action_view/dependency_tracker.rb#L121) but also for `c` or `component` calls would probably be 99% of the needed work. But I don't have the time for that right now so for the time being I'll just call `render` directly from the views instead of doing so from inside the helper 😕.

Thanks again for your response.
