### ISSUE TITLE
Wrong path in generator

### ISSUE THREAD

**Issue by tylerbodway** [progapandist/evil_chat#3]
Just something small I noticed, the path defined in the [component_generator.rb](https://github.com/progapandist/evil_chat/blob/38e220c1a555d9ac22e94e8e34da0415ab8c63ab/lib/generators/component_generator.rb#L22) should read _frontend/_ not _front/_ 

```ruby
def component_path
  "frontend/components/#{component_name}"
end
```

**Comment by progapandist** [comment]
Thanks for noticing, will fix it right away
