### ISSUE TITLE
Accessing session data in ActionCable::Connection

### ISSUE THREAD

**Issue by tylerbodway** [progapandist/evil_chat#9]
I may be missing something so correct me if I'm wrong, but after going through Part 3 I'm receiving an error with my chat:
```
NoMethodError(undefined method `fetch' for nil:NilClass)
```
Which is pointing towards this line inside of the ActionCable [connection.rb](https://github.com/progapandist/evil_chat/blob/868490c25037e866ec6a16af1991c1a055692a68/app/channels/application_cable/connection.rb#L6)
```ruby
self.current_user = request.session.fetch('username', nil)
```

After looking into it, I'm reading that the websocket server does not have access to the session according to the [online docs](http://edgeguides.rubyonrails.org/action_cable_overview.html#notes)

Is this code actually working for you? because I'm not sure how to get around this error and get the username from the session into the connection, if the session is not even available to me

**Comment by tylerbodway** [comment]
Nevermind! It was an issue with my `cable.yml` setup, I apologize, great work love the walkthrough you put together

**Comment by progapandist** [comment]
Thanks! Glad you figured it out :)
